// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puwetaiqqdhpvnxiqgsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1d2V0YWlxcWRocHZueGlxZ3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Njc1ODYsImV4cCI6MjA2ODM0MzU4Nn0._WIOIQO35ggaBRkjrEU0YVgqDb8b0xkSZwlLM2joHfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});